documentation:
  - changed-files:
      - any-glob-to-any-file:
          [
            '**/*.{md,mdx}',
            './docs/**/*',
            '**/*.story.{ts,tsx}',
            '**/*.stories.{ts,tsx}',
          ]

test 🔬:
  - changed-files:
      - any-glob-to-any-file: ['./src/**/*.test.ts']

github actions:
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*']

components:
  - changed-files:
      - any-glob-to-any-file: ['./src/components/**/*']

layout:
  - changed-files:
      - any-glob-to-any-file: ['./src/layout/**/*']

views:
  - changed-files:
      - any-glob-to-any-file: ['./src/views/**/*']
