export const mockText = `
Lorem ipsum odor amet, consectetuer adipiscing elit. Curae magna purus interdum feugiat dui ornare enim luctus in. Varius tempus ante, libero ipsum molestie vitae aliquet gravida natoque. Magna torquent class placerat imperdiet leo eu. Mus nascetur netus scelerisque volutpat lacus eleifend at efficitur inceptos. Ac vitae varius lobortis amet iaculis elementum feugiat lacus netus. Purus mattis pulvinar potenti donec senectus. Rutrum felis malesuada pretium tempus bibendum posuere varius. Euismod nibh interdum facilisis libero at sagittis nisi. Rutrum facilisi litora donec varius habitant elit tempus sollicitudin.

Netus pretium ligula primis finibus facilisi integer torquent. Aliquet habitasse vel lacus porttitor potenti. Feugiat senectus porta tempus, vehicula fermentum per. Tortor magnis consectetur primis interdum vulputate nascetur. Tortor dis luctus rhoncus suspendisse dictum hendrerit? Sagittis et mi; quisque iaculis nunc lectus ac quam. Montes maecenas maximus mauris, efficitur blandit conubia viverra. Auctor cursus augue finibus nisl iaculis himenaeos taciti purus. Maximus potenti vulputate laoreet ullamcorper aliquam commodo. Porta venenatis placerat venenatis ac montes iaculis.

Integer maecenas odio facilisi, cursus eleifend inceptos aptent condimentum magna. Quis taciti purus leo consequat torquent ullamcorper molestie quam. Fermentum parturient cubilia ut natoque; ipsum lobortis vitae aenean eros. Tempor adipiscing tempus class; semper maecenas mi ridiculus. Torquent fusce dui mi elit iaculis ultricies sem dis quis. Dolor praesent ex quam risus amet aenean aliquam taciti. Consequat potenti dui morbi blandit curabitur quisque?

Cubilia metus aenean consectetur praesent bibendum auctor? Mi taciti leo consectetur facilisis vulputate accumsan. Felis molestie sit aliquam donec ex purus ante placerat. Aenean urna egestas bibendum ex donec, convallis sollicitudin. Enim mi natoque efficitur dolor curae porta. Pharetra donec venenatis suspendisse lorem a porttitor id dolor ad. Porttitor at vulputate felis conubia sapien a hac amet ex. Hendrerit id sem dictum volutpat cras nisl. Conubia at purus nunc consequat feugiat laoreet. Morbi dui vel vulputate volutpat convallis dignissim.

Blandit tincidunt primis tincidunt ultricies leo nam dignissim. Ornare dictum mi conubia pulvinar tellus praesent sodales dapibus. Ad scelerisque blandit feugiat cras ullamcorper eget. Massa hendrerit suspendisse lectus at quisque sagittis convallis. Fames massa vivamus vestibulum nisi volutpat id senectus. In libero vitae nullam placerat duis ac. Purus pretium erat risus varius class praesent. Pellentesque habitant nullam ad iaculis elementum eros lorem lectus. Neque cursus nunc dui nunc sollicitudin bibendum.'
`.trim();
